name: Update simulations

on:
  repository_dispatch:
    types: [updated]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Manual update of site'

env:
  CARGO_TERM_COLOR: always

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Ubuntu Required Deps
        run: |
          sudo apt update
          sudo apt install pkg-config libx11-dev libasound2-dev libudev-dev

      - name: Checkout
        uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Update wasm, benchmark data and last_updated timestamps
        run: |
          python -u ./scripts/update.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Simulation static data automatic update
          title: Simulation static data automatic update
          delete-branch: true
